### ISSUE TITLE
PersistenceExtensions.historicState Exception

### ISSUE THREAD

**Issue by bdormael** [ljsquare/SmartVirtualThermostat#1]
I just installed your solution for my 7 rooms.
It looks like it is working fine (via influxdb) but I always get exceptions in the log like an example below for almost each device:
[https://community.openhab.org/t/smart-virtual-thermostat-beta-version/84073/36](url)

Is there anything I’m still doing wrong here ?

**Comment by ljsquare** [comment]
Are you using version 0.2.10? There was a bug in the code. The endHeatTimer wasn't checked for null if power==0.

Anyway, I'm looking in to it. I'm going to test it again with the influxdb (for now a long time I've used the rrd4j database).

**Comment by bdormael** [comment]
Hi,

Yes, I’m using 2.10 (I took the latest code today from Github).
Just to let you know, in the Github version you don’t have the temperature items mentioned which are required by the rules, I copied those from the OpenHab forum version:

Group:Number:AVG	    Temperatures	"Temperaturen"	<temperature>	(Home,Influxdb)
Group:Number:AVG		LivingRoom_Temperatures			    "Woonkamer temperatuur [%.1f °C]"								<temperature>	(LivingRoom,Temperatures)			[ "CurrentTemperature","Temperature", "Measurement"]
Number 				    LivingRoom_Current_Temperature	"Woonkamer temperatuur [%.1f °C]"							<temperature>	(LivingRoom,LivingRoom_Temperatures)				[ "CurrentTemperature" ]			{channel="zwave:device:7308080f:node16:sensor_temperature"}

**Comment by ljsquare** [comment]
Correct, I forgot to create the temperature.items file. Done now.
But you mentioned 7 rooms, in your temperature item file, I only see 1 room.

**Comment by bdormael** [comment]
In the OpenHab post you can see all the rooms:

https://community.openhab.org/t/smart-virtual-thermostat-beta-version/84073/37

**Comment by ljsquare** [comment]
Thanks, In my email I do see all of your items (and your log). In GitHub some how not, it seems to be cut-off.

Anyhow, I see that Rich Koshak has responded. I think also that somehow there is not enough information. I've tried to catch null's and fill them with default values.
But for some reason, I've missed a spot.

**Comment by ljsquare** [comment]
I think I've got it, but it needs to be tested.
Change `val lastTemp = Temperatures.allMembers.filter[name.contains(room)].map[(historicState(new DateTime(lastCalcItem.state.toString),DATABASE).state as Number).doubleValue].reduce[s, v |s+v]/Temperatures.allMembers.filter[name.contains(room)].size` 
to
 `val lastTemp = Temperatures.allMembers.filter[name.contains(room)].map[(historicState(new DateTime(lastCalcItem.state.toString),DATABASE)?.state as Number).doubleValue].reduce[s, v |s+v]/Temperatures.allMembers.filter[name.contains(room)].size `
Mind the little `?` before .state

**Comment by ljsquare** [comment]
Did it work, @radokristof? Then I can close the issue.

**Comment by bdormael** [comment]
Hi, it’s ok, you can close the issue, thx
